### ISSUE TITLE
Blinded by fullscreen

### ISSUE THREAD

**Issue by xoitx** [rjekker/i3-battery-popup#10]
So the pop-up doesn't seem to be "always on top". When I'm on fullscreen mode the pop-up script does it's job but it doesn't show if I'm in fullscreen mode, it's beneath the particular window. So when I exit full screen mode i see the notification then. Sometimes this is too late or I never see it and my laptop goes into disk hibernation or shutsdown.

**Comment by rjekker** [comment]
Unfortunately this is the behaviour of i3wm and I cannot work around that. Fullscreen is fullscreen and it won't allow any popups to show on top of the active window.

**Comment by rjekker** [comment]
On second thought, one thing I never realized: we could try to play a sound instead.. Let's add that as a feature somewhere in the future.
