### ISSUE TITLE
Issue : flock: 200: Bad file descriptor

### ISSUE THREAD

**Issue by edi9999** [rjekker/i3-battery-popup#11]
Hello, I am on ubuntu and get following message when I exit i3-battery-popup : 

```
flock: 200: Bad file descriptor
```

My flock version is as follows : 

flock --version
flock from util-linux 2.31.1

**Comment by rjekker** [comment]
This is interesting.. thank you for the bug report. I will try to solve this when I have time.

**Comment by rjekker** [comment]
Does your system limit the number of open files? Can you try to replace the number 200 in the script with something smaller, let's say 99 (assuming your system allows 100 open files) and see if this works?

**Comment by edi9999** [comment]
I think it has something to do with the fact that for some reason, I had two instances of this script running.

Sorry for the misissue
