### ISSUE TITLE
Feature Request: Play a sound when showing popup

### ISSUE THREAD

**Issue by rjekker** [rjekker/i3-battery-popup#12]
Need to research how to correctly implement this.

**Comment by mjablecnik** [comment]
When you show popup, you can play sound by `aplay` command which is part of alsa-utils..: https://superuser.com/a/511672/648869

**Comment by ljleb** [comment]
Is this still being planned? It's been a while since last update. I would love to have this feature too: sometimes I'm playing games in full-screen, which results in the popup not showing.

**Comment by mjablecnik** [comment]
@lebel-louisjacob if you buy me a Coffee: https://ko-fi.com/applemann
I will implement this feature for you ;)

**Comment by rjekker** [comment]
This feature request is on my list, but unfortunately I don't have time to work on this project at the moment. It might be several months before I can find the time to do that. Any pull requests are very welcome, of course.

**Comment by ljleb** [comment]
@rjekker I just finished #15. Please have a look when you have time.

**Comment by ljleb** [comment]
An option to set the volume of the sound to play could come in handy.

**Comment by ljleb** [comment]
@rjekker I just added the `-v` option to specify the volume of the played sound.

**Comment by rjekker** [comment]
Merged :) Thanks for contributing!
