### ISSUE TITLE
Popup also if battery is full

### ISSUE THREAD

**Issue by xCh12i5** [rjekker/i3-battery-popup#13]
https://github.com/rjekker/i3-battery-popup/blob/5855624d428d8179f099d0369ef4fc7ca5175b12/i3-battery-popup#L106

The `is_battery_discharging()` function does not return in all cases the proper battery state. E.g. if the battery is `full`, there is also no need to display the popup. Maybe it is an improvement to check the battery state in a manner the function name indicates:

`is_battery_discharging() {`
`    cat $BATTERIES | grep "STATUS=Discharging" && return 0`
`    return 1`
`} >/dev/null`

**Comment by rjekker** [comment]
I've updated the script according to your suggestion. Please let me know whether this fixes your problem.

**Comment by qymspace** [comment]
How can I popup when the battery is full?

**Comment by rjekker** [comment]
Hi @qymspace 

This is currently not supported by the script, although it shouldn't be too hard to add. I don't think I'll find the time to do this anytime soon, unfortunately. If you really want this, please add it as a feature request and I'll look into it when I find the time.
