### ISSUE TITLE
Cannot acquire lock

### ISSUE THREAD

**Issue by Leonkoithara** [rjekker/i3-battery-popup#14]
It may be so because I'm missing something but this error is displayed every time the x server is started. I couldn't find any solution online.

**Comment by vybhavab** [comment]
I'm also currently facing the same error. Installed the package from AUR

**Comment by sevaho** [comment]
same

**Comment by sevaho** [comment]
The problem is that the package does not create   ~/.i3-battery-popup.lock so I created it mannualy:

```
 touch ~/.i3-battery-popup.lock
```

**Comment by vybhavab** [comment]
@sevaho worked perfectly. Had to create the i3-battery-popup.lock before installing the package. Thanks for that!

**Comment by rjekker** [comment]
I will probably remove locking completely in the future because this seems to cause problems and it's not necessary for the program to run correctly. It will then be the responsibility of the user to make sure they don't start multiple instances of the program.

**Comment by vybhavab** [comment]
Wanted to update, turned out it doesn't seem to work. Still seems to have the same issue

**Comment by rjekker** [comment]
Please try again. I just removed the code that did the locking. This should be resolved.
