### ISSUE TITLE
Bad error codes

### ISSUE THREAD

**Issue by ljleb** [rjekker/i3-battery-popup#16]
This is minimal, but some error code are not valid according to [this](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html) page.

For instance, an invalid argument should make the command return `22` and not `2`.

**Comment by rjekker** [comment]
You are referring to error codes for system calls in C. There is no need for a shell script to return these codes. I am simply returning different values so that people who need to debug things can see an informative return value.
