### ISSUE TITLE
Is there any way to change the --app-name when using with notify-send

### ISSUE THREAD

**Issue by HeyListenNavi** [rjekker/i3-battery-popup#20]
I use bspwm, and dunst to manage notifications but when the notification its sended the application name is "notify-send" and I would like to change the name using the --app-name parameter, the line of code referenced below will need to change into notify-send -a "appname" -u critical "${1}" ${NOTIFY_OPT}, but i still dont manage to find where the code file is
[Here is picture of how it looks](https://i.imgur.com/Vp1FxT5.png)
[And here is a picture of how I would like it to look](https://i.imgur.com/0SVAFjy.png)
https://github.com/rjekker/i3-battery-popup/blob/d894a102a1ff95019fc59d0a19c89687d502cd1a/i3-battery-popup#L159

**Comment by rjekker** [comment]
Thank you for this input. It will take a few weeks before I can look into this - currently traveling with no development machine on hand. If you could create a pull request, that would be wonderful.

**Comment by HeyListenNavi** [comment]
@rjekker Hey, thanks for the response, i could try but i dont know anything about bash/shell scripting 😆, but i already solved the problem, i just forced the notify-send to always send with the appname as GLaDOS, but i think not everyone would like to have GLaDOS in their notifications
