### ISSUE TITLE
Charged laptop notification

### ISSUE THREAD

**Issue by TheBabu** [rjekker/i3-battery-popup#21]
Hello!

I really like this program, but I do would want one feature to existing:

To have a notification popup when the battery is full. I think most of us know that overcharging ur laptop is a problem.

I think that having this feature won't break the previous version for the most part because it can just be an optional flag. But it would change the `-m` flag because 2 different messages need to included.

Thank you!

**Comment by bra0** [comment]
> Hello!
> 
> I really like this program, but I do would want one feature to existing:
> 
> To have a notification popup when the battery is full. I think most of us know that overcharging ur laptop is a problem.
> 
> I think that having this feature won't break the previous version for the most part because it can just be an optional flag. But it would change the `-m` flag because 2 different messages need to included.

Hello! 
I solved this problem for myself here: [fork](https://github.com/bra0/i3-battery-popup).

**Comment by TheBabu** [comment]
Oh nice @bra0 ! 

Closing this issue.
