### ISSUE TITLE
Difference in battery % from app and status bar

### ISSUE THREAD

**Issue by domix75** [rjekker/i3-battery-popup#24]
Hi
Thanks for this nice piece of code

This is not really an "issue", but strangely enough the % of battery calculated by i3-battery-popup is different than the % shown in the i3 status bar. It's must be calculated differently but I wonder what is the more accurate. It does not prevent it from working anyway since it's a matter of setting the limit.

For instance I had 26% displayed on bottom and the script calculates 31%

![screenshot 2023-09-10 21:54:56](https://github.com/rjekker/i3-battery-popup/assets/66092953/84891d04-5e29-4d1b-a0a6-800d0977b61b)

best
dom

**Comment by rjekker** [comment]
This is probably caused by a difference in how the 2 programs calculate the percentage. I would have to look at the source code for the status bar to see how they do it. As far as I know there is no "official" percentage.
