### ISSUE TITLE
AUR repo

### ISSUE THREAD

**Issue by capocasa** [rjekker/i3-battery-popup#3]
Hi, thanks for making i3-battery-popup!

I created an arch linux AUR user repository package for it, it's here:

https://aur.archlinux.org/packages/i3-battery-popup-git

So now arch users can install it e.g. like so

yaourt -S i3-battery-popup-git

Carlo

**Comment by rjekker** [comment]
Hi Carlo,

Thanks, that's really cool! Will add a line to the documentation :)

**Comment by rjekker** [comment]
Hi Carlo,

I just added a fix to the script for Arch Linux (Arch Linux, kernel 4.12.13-1-ARCH) -- maybe it's a good idea to update the version in the arch repo?

Thanks,

RJ

Carlo Capocasa writes:

> Hi, thanks for making i3-battery-popup!
>
> I created an arch linux AUR user repository package for it, it's here:
>
> https://aur.archlinux.org/packages/i3-battery-popup-git
>
> So now arch users can install it e.g. like so
>
> yaourt -S i3-battery-popup-git
>
> Carlo

--
Reindert-Jan Ekker
reindert@rjekker.nl

**Comment by capocasa** [comment]
HI RJ,

thanks for letting me know, and great!

The package is a -git suffixed package as per the arch repository rules. So it will always install the latest master on installation and upgrade, and arch users expect this behavior.
