### ISSUE TITLE
awk battery percentage

### ISSUE THREAD

**Issue by ergor** [rjekker/i3-battery-popup#4]
A heads up:

I had to modify the script in order to make it work for my system.
Dell XPS 15 9560
Arch Linux, kernel 4.12.13-1-ARCH

The script searches for "ENERGY_FULL_DESIGN" and "ENERGY_NOW" to check battery percentage, but the cat output on my system does not print in that format. I had to modify the script to reflect the following output:

$ cat /sys/class/power_supply/BAT*/uevent 
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11400000
POWER_SUPPLY_VOLTAGE_NOW=12366000
POWER_SUPPLY_CURRENT_NOW=1472000
POWER_SUPPLY_CHARGE_FULL_DESIGN=4912000
POWER_SUPPLY_CHARGE_FULL=4901000
POWER_SUPPLY_CHARGE_NOW=4541000
POWER_SUPPLY_CAPACITY=92
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=DELL 5D91C78
POWER_SUPPLY_MANUFACTURER=LGC-LGC4.64
POWER_SUPPLY_SERIAL_NUMBER=1946

**Comment by rjekker** [comment]
Hi ergor,

Thanks for bringing this to my attention. I added some code to fix this, could you please test this on your system and let me know if it works?

Thanks!

**Comment by ergor** [comment]
Hi!
Just tested the new code, and it is indeed working now!

**Comment by rjekker** [comment]
Thank you, closing the issue
