### ISSUE TITLE
Multi-screen support

### ISSUE THREAD

**Issue by thomai** [rjekker/i3-battery-popup#6]
It would be nice to have some options for multi-screen support. In my case, the dialog opens between two monitors (half of the window on both screens). Would it be possible to open the dialog on each connected screen? Opening it only on the primary screen would be enough as well.

Btw: Thanks for this great script!

**Comment by rjekker** [comment]
How do you run the script? Starting it with -n (using notify-send) should show a popup on your main screen.

Please let me know if that fixes this issue.

Sorry for the late reply, BTW

**Comment by thomai** [comment]
@rjekker Thanks for the hint. It looks like notify-send leads to a popup on the main screen :+1:
