### ISSUE TITLE
Automaticaly shutdown support

### ISSUE THREAD

**Issue by azzamsa** [rjekker/i3-battery-popup#7]
>  lock && systemctl suspend

It would be nice to shutdown automatically when the battery below 5%, sometimes we fall asleep and the computer abruptly shutdown.

I don't realize that I use this script more than 5 months. this is great script, thanks.

**Comment by rjekker** [comment]
Hi, nice to hear you like it!

I'm not aware of a fool-proof way to shutdown the computer that will work everywhere. In some cases you need superuser privileges, etc. So I may need to do a little research.

Here's an idea though: I might add an option to run a command when the lower limit is reached. You might then set this command to pm-suspend, or whatever works on your system. You might still need to fix permissions for pm-suspend.

**Comment by azzamsa** [comment]
I have try this workaround https://github.com/rjekker/i3-battery-popup/pull/9, and it works (but currently only with `wish` installed),

the idea is to give `wish` pop-up timeout so that it will close it self even the user is away/didn't click. then I put a function to check if the battery is critical it will automatically shutdown. 
I use ` systemctl poweroff` and it doesn't need a superuser privileges.

**Comment by azzamsa** [comment]
Thank you for this great script. I use my own [auto-suspend](https://github.com/azzamsa/azzamsa-script/tree/master/auto-suspend) now. :)
