### ISSUE TITLE
Can't move to another workspace with shortcut after using mouse-click for tk

### ISSUE THREAD

**Issue by azzamsa** [rjekker/i3-battery-popup#8]
If I use mouse-click to 'ok' for tk pop-up, I can't move to other i3wm workspace with my keybinding, instead I have to click workspace name with mouse then the error disappear.

**Comment by rjekker** [comment]
Hi,

As far as I know this is an issue with the tk popup, it grabs all keyboard input so the keybinding doesn't reach the window manager. There might be a way to fix this in the wish script - not sure. Will look into this later.

**Comment by azzamsa** [comment]
Thank you for this great script. I use my own [auto-suspend](https://github.com/azzamsa/azzamsa-script/tree/master/auto-suspend) now. :)

As far as I know this issue happens in all tk-based GUI. e.g gitk. So probably I comes from tk it self.
